name = "kolmogorov-complexity"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["KolmogorovComplexity"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "KolmogorovComplexity"
